apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: PLACEHOLDER_REPO_URL
    targetRevision: main
    path: gitops/manifests/secret-store
  destination:
    server: https://kubernetes.default.svc
    namespace: todolist
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    retry: { limit: 10, backoff: { duration: 10s, factor: 2, maxDuration: 3m } }
